[package]
name = "Switchboard"
version = "0.0.1"

[addresses]
std = '0x1'
aptos_framework = '0x1'
# Mainnet Switchboard address: https://github.com/switchboard-xyz/sbv2-aptos#program-ids
switchboard = "07d7e436f0b2aafde60774efb26ccc432cf881b677aca7faaf2a01879bd19fb8"

[dev-addresses]
switchboard = '0x55'

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib/", rev = "mainnet" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib/", rev = "mainnet" }
